---
# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 132
  # Number of characters for headings
  heading_line_length: 132
  # Number of characters for code blocks
  code_block_line_length: 132
