name: CI Pull Request

on:
  pull_request:
    branches-ignore:
      - 'release-please--branches--*'

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/pull-request.yml@40a65158591c1c4b7526d095f2ed58e1c512941f # 
    secrets: inherit
