---
name: "Pull Request"

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches-ignore:
      - "release-please--branches--*"

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_pull_request_callable.yml@5ed58e34d3e7e9dcb3b416e01b8b1a65dbe2f10d
    secrets: inherit
