---
name: "Pull Request"

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches-ignore:
      - "release-please--branches--*"

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_pull_request_callable.yml@cd3a64ec81f3d114a2d7eebcb6b0efd1decb1af6
    secrets: inherit
