---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_release_callable.yml@f8eed6afb89f70c012269a7b7672462014c6793b
    secrets: inherit
