---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_release_callable.yml@ca289f8e32db33d4d6f94e3b91492e958e06af37
    secrets: inherit
