---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_release_callable.yml@cd3a64ec81f3d114a2d7eebcb6b0efd1decb1af6
    secrets: inherit
