---
name: Approve all Renovate PRs automatically

# yamllint disable-line rule:truthy
on: pull_request_target

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/renovate-auto-approve.yml@40a65158591c1c4b7526d095f2ed58e1c512941f # 
    secrets: inherit
