---
name: Approve all Renovate PRs automatically

# yamllint disable-line rule:truthy
on:
  pull_request_target

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_renovate_auto_approve_callable.yml@f8eed6afb89f70c012269a7b7672462014c6793b
    secrets: inherit
