---
name: Approve all Renovate PRs automatically

# yamllint disable-line rule:truthy
on:
  pull_request_target

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_renovate_auto_approve_callable.yml@ca289f8e32db33d4d6f94e3b91492e958e06af37
    secrets: inherit
