---
name: Execute ChatOps command

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types:
      - help-command

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_slash_ops_command_help_callable.yml@4e13a92867f24e0517887f5e6f4c9f9e88b97bef
    secrets: inherit
