---
name: PR commented

# yamllint disable-line rule:truthy
on:
  issue_comment:
    types:
      - created

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_slash_ops_comment_dispatch_callable.yml@f8eed6afb89f70c012269a7b7672462014c6793b
    secrets: inherit
