---
name: Execute ChatOps command

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types:
      - help-command

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_slash_ops_command_help_callable.yml@5ed58e34d3e7e9dcb3b416e01b8b1a65dbe2f10d
    secrets: inherit
