---
name: PR commented

# yamllint disable-line rule:truthy
on:
  issue_comment:
    types:
      - created

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_slash_ops_comment_dispatch_callable.yml@5ed58e34d3e7e9dcb3b416e01b8b1a65dbe2f10d
    secrets: inherit
