---
name: Execute ChatOps command

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types:
      - help-command

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_slash_ops_command_help_callable.yml@621ad2b1ab3f3d6967ac8ecb7614766516002380
    secrets: inherit
