---
name: Execute ChatOps ready command

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types:
      - ready-command

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_slash_ops_command_ready_callable.yml@99c1c2f42731c6a1cd24507e3b262ea77597f053 # 1.26.47
    secrets: inherit
