---
name: "Check spelling"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_spelling_callable.yml@9d28ee22dacd3fba57db6bab6fdcdc10b016ffb8
    secrets: inherit
