---
name: "Check spelling"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_spelling_callable.yml@f8eed6afb89f70c012269a7b7672462014c6793b
    secrets: inherit
