---
name: Close stale issues and PRs

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "25 2 * * *"

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_stale_callable.yml@99c1c2f42731c6a1cd24507e3b262ea77597f053 # 1.26.47
    secrets: inherit
