---
name: "Close stale issues and PRs"

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "25 2 * * *"

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_stale_callable.yml@c8901d1c75611531b7037946d884fd88e1da8e27
    secrets: inherit
