---
name: "Close stale issues and PRs"

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "25 2 * * *"

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_stale_callable.yml@f8eed6afb89f70c012269a7b7672462014c6793b
    secrets: inherit
