---
name: Terraform

# yamllint disable-line rule:truthy
on:
  pull_request:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_module_terraform_callable.yml@5ed58e34d3e7e9dcb3b416e01b8b1a65dbe2f10d
    secrets: inherit
