---
name: Terraform

# yamllint disable-line rule:truthy
on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_module_terraform_callable.yml@40a65158591c1c4b7526d095f2ed58e1c512941f # 
    secrets: inherit
