---
name: Terraform

# yamllint disable-line rule:truthy
on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/terraform_module_terraform_callable.yml@99c1c2f42731c6a1cd24507e3b262ea77597f053 # 1.26.47
    secrets: inherit
    with:
      minimum-terraform-version: "1.5.7"
