name: Test semantic release

on:
  pull_request:

jobs:
  test-semantic-release:
    name: Release dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create dry branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ SECRET }}
        with:
          branch: 'dry-run-release'

      - name: Checkout dry branch
        uses: actions/checkout@v2
        with:
          ref: dry-run-release

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Dry run
        run: unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci

      - name: Back to code
        uses: actions/checkout@v2

      - name: Clear dry branch
        uses: dawidd6/action-delete-branch@v3
        with:
          branches: dry-run-release
