name: Prepare Release PR

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        with:
          release-type: terraform-module
          include-v-in-tag: false
          signoff: "Matthias Kay <matthias.kay@hlag.com>"
          bootstrap-sha: "5213931527b84359dbfe1725e803af318082443f"
          # temporary tokens do not work as they don't have access to protected tags
          token: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
