name: Prepare Release PR

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: google-github-actions/release-please-action@a2d8d683f209466ee8c695cd994ae2cf08b1642d # v4.0.1
        with:
          release-type: terraform-module
          include-v-in-tag: false
          signoff: "Matthias Kay <matthias.kay@hlag.com>"
          bootstrap-sha: "5213931527b84359dbfe1725e803af318082443f"
