name: Prepare Release PR

on:
  push:
    branches:
      - main

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/update-release-pr.yml@40a65158591c1c4b7526d095f2ed58e1c512941f # 
    secrets: inherit
