name: Prepare Release PR

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: google-github-actions/release-please-action@514bc6cdae71484c998108f2136a8f5e4c62b9b9 # v3.7.3
        with:
          release-type: terraform-module
          include-v-in-tag: false
          signoff: "Matthias Kay <matthias.kay@hlag.com>"
          bootstrap-sha: "5213931527b84359dbfe1725e803af318082443f"
